package = "lux-build-test"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = ""
maintainer = "Cootshk"
labels = [ "test" ]
license = "GPL-3.0"

[dependencies]
luastatic = "0.0.12-1"
argparse = "0.7.1-1"
# Add your dependencies here
# `busted = ">=2.0"`

[run]
args = [ "src/main.lua" ]

[build]
type = "builtin"
